/*
 * User Login API
 * API for user authentication
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import org.junit.Test;
import org.junit.Ignore;


/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * User Login
     * <p>
     * Endpoint to authenticate users
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void authApiV1LoginNormalLoginPostTest() throws Exception {
        LoginNormalloginBody body = null;
        InlineResponse200 response = api.authApiV1LoginNormalLoginPost(body);

        // TODO: test validations
    }
}
